### PR TITLE
add xtrx support

### PR DESCRIPTION
**Pull request by dchard**
This pull request adds XTRX SDR support.

Tested with GR 3.8 on Ubuntu 20.04 LTS. Most of the source is from https://github.com/xtrx-sdr/gr-osmosdr with a couple modifications to make it compatible with the latest master of gr-osmosdr.

### CODE REVIEW

**Comment by WilfredoLora** [comment]
@dchard were you able to submit a patch?

**Comment by dchard** [comment]
> @dchard were you able to submit a patch?

I sent it to the osmocom-sdr list as they are not merging here. Did it a week ago, no response yet, but it is not my patch only, so maybe the maintainers are busy with something else.

Non the less I tested my patch against gr-osmosdr master, and it works fine with "osmocom_fft" utility. Gr-fosphor is not yet working, but that is an opengl issue with Ubuntu 20.04 as it seems, so I will try and find a solution hopefully with the help of Sylvain. 

MOD: the patch is now merged to master.

**Comment by curtcorum** [comment]
@RFNOD

please see:

https://github.com/xtrx-sdr/images/issues/83#issuecomment-759127316

for problems building gr-osmosdr with driver built from:

https://github.com/xtrx-sdr/images

**Comment by Dastgsm** [comment]
How about srslte with xtrx? It's didn't yet running even with Soapy?

**Pull request closed without merging**
