### PR TITLE
soapy: allow set_iq_balance_mode if mode == 0 (off)

### PR DESCRIPTION
**Pull request by xloem**

### CODE REVIEW

**Comment by guruofquality** [comment]
I agree with this patch. This patch prevents the exception being throw when the iq balance mode is set to something other than osmosdr::source::IQBalanceOff. I think its critical that we fix the uncaught exception. Thanks and please merge.

**Comment by guruofquality** [comment]
Update: I pushed a version of this fix to the soapy_support branch: http://cgit.osmocom.org/gr-osmosdr/log/?h=soapy_support (this fix uses the osmosdr::source::IQBalanceOff enum, but same idea).

I have a few more fixes, and I will send an email to the osmosdr list. If that gets merged I will post an update here to let everyone know.

**Comment by xloem** [comment]
Thanks so much

**Comment by guruofquality** [comment]
@xloem The soapy support branch has been merged. Feel free to close this issue. And thanks!

**Pull request closed without merging**
